version: "3"
# all the containers have to declare inside services
services:
  # App service
  nestchat:
    build: .
    # image name
    image: mokhaled3003/chatapp
    # container name
    container_name: nestchat
    # always restart the container if it stops.
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - "3000:3000"
    # working directory
    working_dir: /var/www/nest-chat-realtime
    # save (persist) data and also to share data between containers
    volumes:
      - ./:/var/www/nest-chat-realtime
      - /var/www/nest-chat-realtime/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      WAIT_HOSTS: db_mongo:27017
  mongodb:
    image: 'mongo'
    container_name: db_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
